# Generated by Django 4.1.7 on 2023-12-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
    ]
