# Generated by Django 4.1.7 on 2023-12-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_orderinfo_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
